import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Random;
import java.net.URL;

public class Interfaz extends javax.swing.JFrame {
    TrianguloPanel panel = new TrianguloPanel(); 
   
    public Interfaz() {
        initComponents();
        //triangulo.setLayout(null);
        SpinnerModel model = new SpinnerNumberModel(90, 0, 360, 1);
        anguloInput.setModel(model);
        
        
        panel.setSize(panelTriangulo.getSize());
        panel.setLocation(0,0); // Establece la ubicación del TrianguloPanel igual que el triangulo
        
        panel.addMouseMotionListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent e) {
                Double p = panel.triangulo.getPerimetro();
                Double a = panel.triangulo.getArea();
                Double h = panel.triangulo.getAltura();
                double[] lados = panel.triangulo.getLados();
                perimetroPx.setText(""+String.format("%.1f",p));
                areaPx.setText(""+String.format("%.1f",a));
                alturaPx.setText(""+String.format("%.1f",h));
                Avalue.setText(""+String.format("%.1f",lados[0]));
                Bvalue.setText(""+String.format("%.1f",lados[1]));
                Cvalue.setText(""+String.format("%.1f",lados[2]));
            }
        });
        
        panelTriangulo.add(panel);
        panel.calcularElementos();
        Double p = panel.triangulo.getPerimetro();
        Double a = panel.triangulo.getArea();
        Double h = panel.triangulo.getAltura();
        double[] lados = panel.triangulo.getLados();
        perimetroPx.setText(""+String.format("%.1f",p));
        areaPx.setText(""+String.format("%.1f",a));
        alturaPx.setText(""+String.format("%.1f",h));
        Avalue.setText(""+String.format("%.1f",lados[0]));
        Bvalue.setText(""+String.format("%.1f",lados[1]));
        Cvalue.setText(""+String.format("%.1f",lados[2]));
        panel.repaint();
    }
    
    public Interfaz(TrianguloPanel triangulo) {
        initComponents();
        //triangulo.setLayout(null);
        
        panel.setSize(panelTriangulo.getSize());
        panel.setLocation(0,0); // Establece la ubicación del TrianguloPanel igual que el triangulo
        
        panel.addMouseMotionListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent e) {
                Double p = panel.triangulo.getPerimetro();
                Double a = panel.triangulo.getArea();
                Double h = panel.triangulo.getAltura();
                double[] lados = panel.triangulo.getLados();
                perimetroPx.setText(""+String.format("%.1f",p));
                areaPx.setText(""+String.format("%.1f",a));
                alturaPx.setText(""+String.format("%.1f",h));
                Avalue.setText(""+String.format("%.1f",lados[0]));
                Bvalue.setText(""+String.format("%.1f",lados[1]));
                Cvalue.setText(""+String.format("%.1f",lados[2]));
                
            }
        }); 
        panelTriangulo.add(panel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cambiarPuntosBoton = new javax.swing.JButton();
        rotarTrianguloButton = new javax.swing.JButton();
        cambiarColorBoton = new javax.swing.JButton();
        estadoPuntos = new javax.swing.JCheckBox();
        estadoColor = new javax.swing.JButton();
        anguloInput = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        perimetroPx = new javax.swing.JLabel();
        areaPx = new javax.swing.JLabel();
        alturaPx = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Avalue = new javax.swing.JLabel();
        Bvalue = new javax.swing.JLabel();
        Cvalue = new javax.swing.JLabel();
        panelTriangulo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trianguloLogo.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(153, 0, 204));

        jLabel2.setFont(new java.awt.Font("Terminator Two", 0, 18)); // NOI18N
        jLabel2.setText("Modificaciones");

        cambiarPuntosBoton.setFont(new java.awt.Font("Terminator Two", 0, 12)); // NOI18N
        cambiarPuntosBoton.setText("Cambiar puntos");
        cambiarPuntosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarPuntosBotonActionPerformed(evt);
            }
        });

        rotarTrianguloButton.setFont(new java.awt.Font("Terminator Two", 0, 12)); // NOI18N
        rotarTrianguloButton.setText("ROTAR TRIANGULO");
        rotarTrianguloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotarTrianguloButtonActionPerformed(evt);
            }
        });

        cambiarColorBoton.setFont(new java.awt.Font("Terminator Two", 0, 12)); // NOI18N
        cambiarColorBoton.setText("Cambiar color");
        cambiarColorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarColorBotonActionPerformed(evt);
            }
        });

        estadoPuntos.setFocusable(false);
        estadoPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoPuntosActionPerformed(evt);
            }
        });

        estadoColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoColorActionPerformed(evt);
            }
        });

        anguloInput.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                anguloInputStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cambiarColorBoton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cambiarPuntosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(estadoPuntos)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(estadoColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rotarTrianguloButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(anguloInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambiarPuntosBoton)
                    .addComponent(estadoPuntos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cambiarColorBoton)
                    .addComponent(estadoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anguloInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotarTrianguloButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(153, 0, 204));

        jLabel3.setFont(new java.awt.Font("Terminator Two", 0, 18)); // NOI18N
        jLabel3.setText("Datos");

        jLabel4.setText("Perimetro:");

        jLabel5.setText("Area:");

        jLabel6.setText("Altura:");

        perimetroPx.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        perimetroPx.setText("0px");

        areaPx.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        areaPx.setText("0px");

        alturaPx.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        alturaPx.setText("0px");

        jLabel7.setText("A =");

        jLabel8.setText("B =");

        jLabel9.setText("C =");

        Avalue.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        Avalue.setText("0px");

        Bvalue.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        Bvalue.setText("0px");

        Cvalue.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        Cvalue.setText("0px");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perimetroPx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(areaPx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alturaPx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Avalue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bvalue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cvalue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(perimetroPx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(areaPx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(alturaPx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Avalue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Bvalue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Cvalue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTriangulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelTrianguloMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelTrianguloMouseMoved(evt);
            }
        });
        panelTriangulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelTrianguloFocusGained(evt);
            }
        });
        panelTriangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelTrianguloMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelTrianguloLayout = new javax.swing.GroupLayout(panelTriangulo);
        panelTriangulo.setLayout(panelTrianguloLayout);
        panelTrianguloLayout.setHorizontalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );
        panelTrianguloLayout.setVerticalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(panelTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarPuntosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarPuntosBotonActionPerformed
        panel.setPuntosEditables(!panel.getPuntosEditables());
        estadoPuntos.setSelected(panel.getPuntosEditables());
    }//GEN-LAST:event_cambiarPuntosBotonActionPerformed

    private void rotarTrianguloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotarTrianguloButtonActionPerformed
        try{
            panel.rotarTriangulo();
        }catch(TrianguloDesbordadoException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_rotarTrianguloButtonActionPerformed

    private void cambiarColorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarColorBotonActionPerformed
        panel.changeTriangleColor();
        estadoColor.setBackground(panel.triangulo.getColor());
    }//GEN-LAST:event_cambiarColorBotonActionPerformed

    private void panelTrianguloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTrianguloMouseDragged
        Double p = panel.triangulo.getPerimetro();
        Double a = panel.triangulo.getArea();
        Double h = panel.triangulo.getAltura();
        perimetroPx.setText(""+p);
        areaPx.setText(""+a);
        alturaPx.setText(""+h);
    }//GEN-LAST:event_panelTrianguloMouseDragged

    private void panelTrianguloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTrianguloMousePressed
        System.out.println("Abriendo panel");
        Double p = panel.triangulo.getPerimetro();
        Double a = panel.triangulo.getArea();
        Double h = panel.triangulo.getAltura();
        perimetroPx.setText(""+p);
        areaPx.setText(""+a);
        alturaPx.setText(""+h);
    }//GEN-LAST:event_panelTrianguloMousePressed

    private void panelTrianguloMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTrianguloMouseMoved
        System.out.println("Abriendo panel");
        Double p = panel.triangulo.getPerimetro();
        Double a = panel.triangulo.getArea();
        Double h = panel.triangulo.getAltura();
        perimetroPx.setText(""+p);
        areaPx.setText(""+a);
        alturaPx.setText(""+h);
    }//GEN-LAST:event_panelTrianguloMouseMoved

    private void panelTrianguloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelTrianguloFocusGained
        System.out.println("Abriendo panel");
    }//GEN-LAST:event_panelTrianguloFocusGained

    private void estadoPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoPuntosActionPerformed
        panel.setPuntosEditables(!panel.getPuntosEditables());
        estadoPuntos.setSelected(panel.getPuntosEditables());
    }//GEN-LAST:event_estadoPuntosActionPerformed

    private void estadoColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoColorActionPerformed
        Color colorSeleccionado = JColorChooser.showDialog(null, "Selecciona un Color", Color.BLACK);
                
        if (colorSeleccionado != null) {
            // Muestra la información del color seleccionado
            System.out.println("Color seleccionado: " + colorSeleccionado);
            panel.triangulo.setColor(colorSeleccionado);
            estadoColor.setBackground(colorSeleccionado);
            panel.repintar();
        }
    }//GEN-LAST:event_estadoColorActionPerformed

    private void anguloInputStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_anguloInputStateChanged
        System.out.println("Cambiaste el angulo a " + anguloInput.getValue());
        panel.setAnguloDeRotacion((int)anguloInput.getValue());
    }//GEN-LAST:event_anguloInputStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Avalue;
    private javax.swing.JLabel Bvalue;
    private javax.swing.JLabel Cvalue;
    private javax.swing.JLabel alturaPx;
    private javax.swing.JSpinner anguloInput;
    private javax.swing.JLabel areaPx;
    private javax.swing.JButton cambiarColorBoton;
    private javax.swing.JButton cambiarPuntosBoton;
    private javax.swing.JButton estadoColor;
    private javax.swing.JCheckBox estadoPuntos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelTriangulo;
    private javax.swing.JLabel perimetroPx;
    private javax.swing.JButton rotarTrianguloButton;
    // End of variables declaration//GEN-END:variables
}
